import {v4 as uuidv4} from "uuid";
const rating=[1,2,3,4,5];
export const products = [
    {
        id:uuidv4(),
        imgSrc:"https://i.ibb.co/zGNxZpc/product-image.webp",
        title:"Roadster",
        subtitle:"men casual shirt",
        price:"599",
        MRP:"1499",
        discount:"60",
        inStock:true,
        category:"Shirt",
        rating:rating[Math.floor(Math.random()*rating.length)],
        quantity:1,
        },
    {
        id:uuidv4(),
        imgSrc:"https://i.ibb.co/2vQxtqK/shirt-2.webp",
        title:"Highlander",
        subtitle:"men casual shirt",
        price:"799",
        MRP:"1599",
        discount:"50",
        inStock:true,
        category:"Shirt",
        rating:rating[Math.floor(Math.random()*rating.length)],
        quantity:1,
    },
    {
        id:uuidv4(),
        imgSrc:"https://i.ibb.co/t2CjBs5/shirt-3.webp",
        title:"Flying Machine",
        subtitle:"men casual shirt",
        price:"999",
        MRP:"1999",
        discount:"50",
        inStock:true,
        category:"Shirt",
        rating:rating[Math.floor(Math.random()*rating.length)],
        quantity:1,
    },
    {
        id:uuidv4(),
        imgSrc:"https://i.ibb.co/BN5Vrr3/tshirt1.webp",
        title:"Ether",
        subtitle:"men casual t-shirt",
        price:"599",
        MRP:"1499",
        discount:"60",
        inStock:true,
        category:"T-Shirt",
        rating:rating[Math.floor(Math.random()*rating.length)],
        quantity:1,
    },
    {
        id:uuidv4(),
        imgSrc:"https://i.ibb.co/NssS5St/tshirt2.webp",
        title:"Roadster",
        subtitle:"men casual t-shirt",
        price:"399",
        MRP:"999",
        discount:"60",
        inStock:true,
        category:"T-Shirt",
        rating:rating[Math.floor(Math.random()*rating.length)],
        quantity:1,
    },
    {
        id:uuidv4(),
        imgSrc:"https://i.ibb.co/7nS2BTD/tshirt3.webp",
        title:"Zara",
        subtitle:"women casual t-shirt",
        price:"799",
        MRP:"1599",
        discount:"50",
        inStock:true,
        category:"T-Shirt",
        rating:rating[Math.floor(Math.random()*rating.length)],
        quantity:1,
    },
    {
        id:uuidv4(),
        imgSrc:"https://i.ibb.co/RhsbxWt/tshirt4.webp",
        title:"DressBerry",
        subtitle:"women casual t-shirt",
        price:"399",
        MRP:"999",
        discount:"60",
        inStock:false,
        category:"T-Shirt",
        rating:rating[Math.floor(Math.random()*rating.length)],
        quantity:1,
    },
    {
        id:uuidv4(),
        imgSrc:"https://i.ibb.co/0VBKmQb/cart-image.jpg",
        title:"Wrogn",
        subtitle:"men casual shirt",
        price:"999",
        MRP:"1999",
        discount:"60",
        inStock:false,
        category:"Shirt",
        rating:rating[Math.floor(Math.random()*rating.length)],
        quantity:1,
    },

] 





